# Generated by Django 3.0.1 on 2020-01-17 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=12)),
                ('mobile_no', phone_field.models.PhoneField(blank=True, max_length=20)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('about', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(upload_to='')),
                ('location', models.CharField(max_length=50, verbose_name='Office location')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
                'unique_together': {('user_id', 'gender', 'mobile_no', 'location')},
            },
        ),
    ]
